# Generated by Django 6.0.3 on 2026-03-25 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categort',
            new_name='category',
        ),
    ]
